#!/bin/bash
shopt -s expand_aliases
source $GOPATH/src/github.com/onosproject/onos-config/build/bash_aliases

# Re-create the cluster
onit delete cluster
onit create cluster

# Stage some files on the onos-cli node for creating roles, etc.
okctl cp $GOPATH/src/github.com/onosproject/onos-ztp/test/samplejson/peer.json $(okpid cli):/tmp
okctl cp $GOPATH/src/github.com/onosproject/onos-ztp/test/samplejson/spine.json $(okpid cli):/tmp
okctl cp $GOPATH/src/github.com/onosproject/onos-ztp/test/samplejson/leaf.json $(okpid cli):/tmp

# Load the ZTP app
onit add app --image onosproject/onos-ztp:latest onos-ztp

# Create the roles
ocli onos ztp add role /tmp/peer.json
ocli onos ztp add role /tmp/spine.json
ocli onos ztp add role /tmp/leaf.json

# Add our leaf devices, but as peers
ocli onos topo add device wedge1 --address 10.128.13.221:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer
ocli onos topo add device wedge2 --address 10.128.13.222:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer

# Add our spine
ocli onos topo add device wedge3 --address 10.128.13.223:28000 --type Stratum --version 1.0.0 --plain --insecure --role spine

echo "Press enter to switch peers to leaves..."
read foo

# Change leaves into proper leaves
ocli onos topo update device wedge1 --address 10.128.13.221:28000 --type Stratum --version 1.0.0 --plain --insecure --role leaf
ocli onos topo update device wedge2 --address 10.128.13.222:28000 --type Stratum --version 1.0.0 --plain --insecure --role leaf
