sudo: false

language: go

go:
  - '1.14.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
  - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

jobs:
  include:
    - stage: tests
      script:
        - make coverage
    - stage: docs build
      if: type != pull_request
      script:
        - sh ../build-tools/build/travis/trigger-travis onosproject onos-docs master "`git rev-parse --short HEAD`" $TRAVIS_ACCESS_TOKEN
    - stage: CLI build
      if: type != pull_request
      script:
        - sh ../build-tools/build/travis/trigger-travis onosproject onos-cli master "`git rev-parse --short HEAD`" $TRAVIS_ACCESS_TOKEN
    - stage: release
      if: type != pull_request && fork == false
      script:
        - bash ./build/bin/push-images