// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/northbound/proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/northbound/proto/service.proto", fileDescriptor_01f1463e64268a46) }

var fileDescriptor_01f1463e64268a46 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcb, 0x2f, 0x2a, 0xc9, 0x48, 0xca, 0x2f, 0xcd, 0x4b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94, 0x11,
	0x0f, 0x17, 0x57, 0x54, 0x48, 0x40, 0x30, 0x44, 0x2a, 0x89, 0x0d, 0x2c, 0x68, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x15, 0x32, 0x2b, 0x09, 0x41, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZTPServiceClient is the client API for ZTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZTPServiceClient interface {
}

type zTPServiceClient struct {
	cc *grpc.ClientConn
}

func NewZTPServiceClient(cc *grpc.ClientConn) ZTPServiceClient {
	return &zTPServiceClient{cc}
}

// ZTPServiceServer is the server API for ZTPService service.
type ZTPServiceServer interface {
}

// UnimplementedZTPServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZTPServiceServer struct {
}

func RegisterZTPServiceServer(s *grpc.Server, srv ZTPServiceServer) {
	s.RegisterService(&_ZTPService_serviceDesc, srv)
}

var _ZTPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ZTPService",
	HandlerType: (*ZTPServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/northbound/proto/service.proto",
}
