// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/admin/admin.proto

// Package admin defines the administrative and diagnostic gRPC interfaces.

package admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/admin/admin.proto", fileDescriptor_d6b467461202c036) }

var fileDescriptor_d6b467461202c036 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x83, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60,
	0x8e, 0x91, 0x20, 0x17, 0x7f, 0x54, 0x49, 0x81, 0x23, 0x88, 0x1d, 0x9c, 0x5a, 0x54, 0x96, 0x99,
	0x9c, 0x9a, 0xc4, 0x06, 0x56, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xec, 0xd6, 0xf8,
	0x39, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZtpAdminServiceClient is the client API for ZtpAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZtpAdminServiceClient interface {
}

type ztpAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewZtpAdminServiceClient(cc *grpc.ClientConn) ZtpAdminServiceClient {
	return &ztpAdminServiceClient{cc}
}

// ZtpAdminServiceServer is the server API for ZtpAdminService service.
type ZtpAdminServiceServer interface {
}

// UnimplementedZtpAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZtpAdminServiceServer struct {
}

func RegisterZtpAdminServiceServer(s *grpc.Server, srv ZtpAdminServiceServer) {
	s.RegisterService(&_ZtpAdminService_serviceDesc, srv)
}

var _ZtpAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.ZtpAdminService",
	HandlerType: (*ZtpAdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/admin/admin.proto",
}
